# -*- coding: utf-8 -*-
"""1 Gün.ipynb adlı not defterinin kopyası

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g5VFLEhdt-YfMHQo8ELuuJU8JbQPamBx
"""

print('Hello World')

print('Hello1')

print('Hello2')
print('Hello3')
print('Hello4')

1 #yorum yazıyorum
2 #notlar alıyorum

n=1
print(n)
n

n=5
print(n)
n

p=n
print(p)

hello='World'

1 print(Hello)
2 print('World')
3 hello

t=3.5
print(type(p)) #float

1 t,f=True,False #boolean
2 print(type(t))

hakan= 'hakan koş'
hakan

print(len(hakan))

name= 'Hakan'
print(f'Hello {name}') #F-String

5**2

35+67

'35+87+90+45'

'35'*3

'hello'*4

x=10

print(x+2)
print(x-2)
print(x*2)
print(x**2)
print(x/2)
print(x//2)
print(x%2)

z=6
z+=1
# z=z+1