# -*- coding: utf-8 -*-
"""3.Gün.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nvEOr4P5TYhZVGcYyt3dzpG0SvzHvfus
"""

sayi=int(input('4'))

if sayi<0 :
    sayi*=-4

course='python'

s=input('b')

 if s in course
 

  print('Mevcut!')
 else:
  print('Yok...')

score=int(input('Lütfen sınav puanınızı girin '))

   if score <=40
      print('Kötü,çok çalışmalısın..')
  elif score <=60

x=5

if x<4:
   x=x+1
elif x<5:
   x=x+2   
if  x<7:
   x=x+3
print('x in değeri,',x)

maas=float(input('maasınızı girin'))

if maas<0:
  print('Geçersiz değer')
else:

   if 0<maas<=1000:
     maas=maas+maas*0.15
   elif maas<=2000:

sayi=0

while sayi <9:
  print('Sayının değeri:',sayi)
  sayi=sayi+1

sayi2=0

while sayi2 !=9:
    print('Sayının değeri:',sayi2)
    sayi2 +=2

sayi3 =int(input('Lütfen 1 ve 10 arasında bir sayi giriniz:'))

while sayi3 < 1 or sayi3 >10:
  print('Doğru olmayan bir değer girdiniz!!!')
  sayi3 =int(input('Lütfen 1 ve 10 arasında sayi giriniz:'))
  print('Tebrikler...')

t = [1,2,3,4,5,6,7,8,9,10]

i = 0
while (i < len(t)):
  print(i,'.indexteki elemanı:',t[i])
  i+=1

while True:
 a = input('Bir değer giriniz: ')
 if a== 'Exit':
  break

for i in [2,45,57]:
 print(i)

for i in range(5):
  print:(i)

for i in 'Python Kursu':
  print(i)

for i in 'Python Kursu'.split():
  print(i)

for i in range(10):
 if i==5:
   break
 print(i)

sayilar = list(range(8))

kareler = []

for i in sayilar:
  kareler.appened(i**2)
  print(kareler)

sayilar = list(range(8))

kareler = [i**2
           for i in sayilar]
print(kareler)

sayilar = list(range(8))

cift_kareler = [i**2
                for i in sayilar
                if i % 2 ==0]

tek_küpler = [i**3
              for i in sayilar
              if i% 2 ==1

print(cift_kareler)
      
print(tek_küpler)