# -*- coding: utf-8 -*-
"""4.Gün

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d9ztI7xzriGluWZ3Arkh2732Si_gjzl2
"""

list1 = [1,2,3]
list2 = [4,5,6]

list3 = [a+b
         for a,b in zip(list1,list2)]
print(list3)

stop_number = int(input('Bir bitiş sayısı giriniz'))

sounuc = 0
for i in range(1, stop_number):
  sonuc += i 

print(sonuc)

import random as rnd 


gizli = rnd.randint(1,100)
check = False

#tahmin = int(input('Bir tahmin giriniz'))


for x in range(6):
  tahmin = int(input('Bir tahmin giriniz'))
  if tahmin == gizli:
    print('Tebrikler')
    check = True
    break
  elif tahmin < gizli: 
     print('Daha büyük bir sayı giriniz!!')
  else:
      print('Daha küçük bir sayı giriniz!!')
if not check:
      print('Bilemediniz, belirlenen sayı:',gizli)

d = {}

print(d)

d ={'print':1,'course':2}
print(d)

d2 = {'machine':'learning','artifical':'intelligence'}
d2

d2['artifical']

d['course']

d2['deep'] = 'learning'
d2
#print(d2)

print(d.keys())

d2.values()

d2.items()

for k in d2.keys():
  print(k)

for v in d.values():
  print(v)

for k,v in d2.items():
  print(k,v)

for k,v in d.items():
  if v == 2:
    print(k)

#listeden sözlük oluşturma


sayilar = list(range(9))

cift_kare = {x: x**2
             for x in sayilar
             if x % 2  ==0}
print(cift_kare)

s = {'python',5,6,8,5,6,'abc','python'}
print(s)

from math import sqrt

#import math

print({sqrt(x) for x in list(range(10))})

demet = (1,2,3,4,5)
print(demet)
print(type(demet))

dm3 = ('hakan',5,8, 'mart')
dm3.index('mart')