# -*- coding: utf-8 -*-
"""6.Gün

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_FTw2RdW-zFzKI3-dprkXPvU_0iK7Hvi
"""

#exception lara bir diğer örnek, ZeroDivisionError

sayi3 = int(input('ilk sayı: '))
sayi4 = int(input('İkinci sayı: '))


print(sayi3,'/',sayi4, '=', sayi3/sayi4)

try:
  int(x)

expect ValueError:
   print('Lütfen integer bir değer giriniz!!!')

sayi3 = input('İlk sayı: ')
sayi4 = input('İkinci sayı: ')

try:
  sayi3_int = int(sayi3)
  sayi4_int = int(sayi4)

def terscevir(s):
   
   if (type(s)) != str):
     raise ValueError('Lütfen bir string değeri girin.')
   else:
     return s[::-1]

terscevir('python')

class Car() :
  renk = 'kırmızı'
  marka = 'art'
  kapi = 5

araba1 = Car() :

print(araba1)

araba2 = Car()

araba2.renk

dir(araba2)

class Car2():

  def _init_(self):
    print('init methodu çağrıldı...')

car = Car2()

class Car3():

  def _init_(self,renk,marka,kapi):
    self.renk = renk
    self.marka = marka
    self.kapi = kapi


kirmizi_araba = Car3('kırmızı','abc',2)

sari_araba = Car3('sarı','xyz', 4)

print(kirmizi_araba.renk)
print(sari_araba.marka)

mavi_araba = Car3()