# -*- coding: utf-8 -*-
"""Veri Seti.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rhk4stRJbwyUdS7jK0AEGtJH8wGPLW1m
"""

import nltk
from  nltk.corpus import twitter_samples
import matplotlib.pyplot as plt
import random

